image: docker:stable

stages:
  - Build trigger

docker build:
  stage: Build trigger
  script:
  - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.example.com/api/v4/projects/9/trigger/pipeline
  only:
  - tags


